# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_delft", "0002_nft"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFT_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
