# Generated by Django 4.2.4 on 2023-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_delft", "0003_nft_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft_address",
            name="nftId",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
